services:
  ingestion:
    build: ./ingestion
    env_file:
      - ./.env               
    volumes:
      - ./ingestion/dataset:/app/dataset
      - ./ingestion/data/vector_store:/app/data/vector_store
    ports:
      - "5002:5002"

  backend:
    build: ./backend
    env_file:
      - ./.env
    ports:
      - "5001:5001"
    volumes:
      - ./backend/src:/app/src

  llm-service:
    build: ./llm-service
    env_file:
      - ./.env
    ports:
      - "5003:5003"
    volumes:
      - ./llm-service/src:/app/src
      - ./llm-service/logs:/app/logs

  # crawler:
  #   build: ./crawler
  #   # env_file:
  #   #   - ./.env
  #   #   - ./crawler/.env

  # llm-service:
  #   build: ./llm-service
  #   # env_file:
  #   #   - ./.env
  #   #   - ./llm-service/.env

